**Exercise 2**

1 Can you spot the obvious error?

 coords[:, 1], coords[:, 1] we have repeated assignment on the right side. it should be like this:
 coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3], = coords[:, 1], **coords[:, 0]**, coords[:, 3], coords[:, 2]

2 After fixing the obvious error it is still wrong, how can this be fixed?

The line coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3], = coords[:, 1], coords[:, 1], coords[:, 3], coords[:, 2]

attempts to perform multiple assignments simultaneously.
In Python, this syntax is not allowed for modifying arrays. we should use temporary variable or Slicing with Assignment as below

In [53]:
import numpy as np

In [54]:
# corrected code:

def swap(coords: np.ndarray):

    coords[:, [0, 1]], coords[:, [2, 3]] = coords[:, [1, 0]], coords[:, [3, 2]]
    return coords



# Corrected code

In [55]:
coords = np.array([[10, 5, 15, 6, 0],
                   [11, 3, 13, 6, 0],
                   [5, 3, 13, 6, 1],
                   [4, 4, 13, 6, 1],
                   [6, 5, 13, 16, 1]])

print('original array:')
print("| x1 | y1 | x2 | y2 | class |")
print(coords)

swapped_coords = swap(coords)

print('swaped array:')
print("| x1 | y1 | x2 | y2 | class |")
print(swapped_coords)


original array:
| x1 | y1 | x2 | y2 | class |
[[10  5 15  6  0]
 [11  3 13  6  0]
 [ 5  3 13  6  1]
 [ 4  4 13  6  1]
 [ 6  5 13 16  1]]
swaped array:
| x1 | y1 | x2 | y2 | class |
[[ 5 10  6 15  0]
 [ 3 11  6 13  0]
 [ 3  5  6 13  1]
 [ 4  4  6 13  1]
 [ 5  6 16 13  1]]
